version: "3"
services:
  mysqldb:
    image: mysql:8
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=employee
    networks:
      - my-network
    ports:
      - "3306:3306"

  app:
    depends_on:
      - mysqldb
    build:
      context: ./docker-demo
      dockerfile: Dockerfile
    networks:
      - my-network
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/employee?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true",
          "spring.datasource.username" : "root",
          "spring.datasource.password" : "root",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
          "spring.jpa.hibernate.ddl-auto" : "update"
        }'

networks:
  my-network: